name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.5
          cache: true
          cache-sdk: true
      - uses: bluefireteam/melos-action@v3
      - run: melos bootstrap
      - run: action-validator .github/workflows/ci.yaml
      - run: melos format:check
      - run: melos analyze

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.5
          cache: true
          cache-sdk: true
      - uses: bluefireteam/melos-action@v3
      - run: melos bootstrap
      - run: melos test:dart:unit

  test-integration:
    runs-on: ubuntu-latest
    # services:
    #   devnet:
    #     options: --name devnet-service
    #     image: shardlabs/starknet-devnet-rs:0.0.5
    #     ports:
    #       - 5050:5050
    steps:
      - uses: actions/checkout@v2
      - uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.5
          cache: true
          cache-sdk: true
      - uses: bluefireteam/melos-action@v3
      - run: melos bootstrap
      # - run: docker cp ./assets/devnet-dump.json devnet-service:devnet-dump.json
      - name: Run starknet-devnet as a background process
        run: |
          docker run -d --name starknet-devnet \
            -v ${{ github.workspace }}/assets/devnet-dump.json:/usr/local/bin/devnet-dump.json \
            --entrypoint tini \
            shardlabs/starknet-devnet-rs:0.0.5 -- \
            starknet-devnet --host 0.0.0.0 --seed 0 --dump-path /usr/local/bin/devnet-dump.json
      - name: Wait for starknet-devnet to be ready
        run: |
          while ! nc -z localhost 5000; do   
            echo "Waiting for starknet-devnet to start..."
            sleep 1
          done
      - run: melos test:dart:integration
