name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
      - uses: bluefireteam/melos-action@v3
      - run: melos bootstrap
      - run: melos format:check
      - run: melos analyze

  test-unit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
      - uses: bluefireteam/melos-action@v3
      - run: melos bootstrap
      - run: melos test:dart:unit

  test-integration:
    runs-on: ubuntu-latest
    needs: lint
    services:
      devnet:
        image: shardlabs/starknet-devnet-rs:0.0.5
        ports:
          - 5050:5050
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
      - uses: bluefireteam/melos-action@v3
      - run: melos bootstrap
      - run: melos test:dart:integration
